version: "3"

services:
  sic_landing:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - .:/sic_landing

