export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_SIGNUP_SUCCEEDED = "USER_SIGNUP_SUCCEEDED";

export const AUTH_DELETE_VALUE = "AUTH_DELETE_VALUE";
export const AUTH_VALUE_CHANGED = "AUTH_VALUE_CHANGED";

export const DELETE_VALUE = "DELETE_VALUE";
export const VALUE_CHANGED = "VALUE_CHANGED";

export const FETCH_HOMEPAGE_DATA = "FETCH_HOMEPAGE_DATA";
export const FETCH_HOMEPAGE_DATA_FAILED = "FETCH_HOMEPAGE_DATA_FAILED";
export const FETCH_HOMEPAGE_DATA_SUCCEEDED = "FETCH_HOMEPAGE_DATA_SUCCEEDED";

export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_FAILED = "FETCH_COUNTRIES_FAILED";
export const FETCH_COUNTRIES_SUCCEEDED = "FETCH_COUNTRIES_SUCCEEDED";

export const FETCH_SUGGESTED_COURSES = "FETCH_SUGGESTED_COURSES";
export const FETCH_SUGGESTED_COURSES_FAILED = "FETCH_SUGGESTED_COURSES_FAILED";
export const FETCH_SUGGESTED_COURSES_SUCCEEDED =
  "FETCH_SUGGESTED_COURSES_SUCCEEDED";

export const COURSE_SEARCH = "COURSE_SEARCH";
export const COURSE_SEARCH_FAILED = "COURSE_SEARCH_FAILED";
export const COURSE_SEARCH_SUCCEEDED = "COURSE_SEARCH_SUCCEEDED";

export const FETCH_FILTERS = "FETCH_FILTERS";
export const FETCH_FILTERS_FAILED = "FETCH_FILTERS_FAILED";
export const FETCH_FILTERS_SUCCEEDED = "FETCH_FILTERS_SUCCEEDED";

export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
export const FETCH_ADDRESSES_FAILED = "FETCH_ADDRESSES_FAILED";
export const FETCH_ADDRESSES_SUCCEEDED = "FETCH_ADDRESSES_SUCCEEDED";

//profile actions
export const FETCH_OTHER_TESTS = "FETCH_OTHER_TESTS";
export const FETCH_OTHER_TESTS_FAILED = "FETCH_OTHER_TESTS_FAILED";
export const FETCH_OTHER_TESTS_SUCCEEDED = "FETCH_OTHER_TESTS_SUCCEEDED";

export const FETCH_ENGLISH_TESTS = "FETCH_ENGLISH_TESTS";
export const FETCH_ENGLISH_TESTS_FAILED = "FETCH_ENGLISH_TESTS_FAILED";
export const FETCH_ENGLISH_TESTS_SUCCEEDED = "FETCH_ENGLISH_TESTS_SUCCEEDED";

export const FETCH_EDUCATION = "FETCH_EDUCATION";
export const FETCH_EDUCATION_FAILED = "FETCH_EDUCATION_FAILED";
export const FETCH_EDUCATION_SUCCEEDED = "FETCH_EDUCATION_SUCCEEDED";

export const FETCH_INTERESTS = "FETCH_INTERESTS";
export const FETCH_INTERESTS_FAILED = "FETCH_INTERESTS_FAILED";
export const FETCH_INTERESTS_SUCCEEDED = "FETCH_INTERESTS_SUCCEEDED";

export const FETCH_APPLICATIONS = "FETCH_APPLICATIONS";
export const FETCH_APPLICATIONS_FAILED = "FETCH_APPLICATIONS_FAILED";
export const FETCH_APPLICATIONS_SUCCEEDED = "FETCH_APPLICATIONS_SUCCEEDED";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";
export const FETCH_MESSAGES_SUCCEEDED = "FETCH_MESSAGES_SUCCEEDED";

export const FETCH_ADS = "FETCH_ADS";
export const FETCH_ADS_FAILED = "FETCH_ADS_FAILED";
export const FETCH_ADS_SUCCEEDED = "FETCH_ADS_SUCCEEDED";

export const FETCH_BUDGET = "FETCH_BUDGET";
export const FETCH_BUDGET_FAILED = "FETCH_BUDGET_FAILED";
export const FETCH_BUDGET_SUCCEEDED = "FETCH_BUDGET_SUCCEEDED";
